### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by Tempest-5ky** [BelgianSalamander/MoreBundles#14]
Hey! Got a crash on 1.18.2, mod version 1.2.0

Crashlog: https://mclo.gs/rbHC9Ty

**Comment by RichPrune** [comment]
same here The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "me.salamander.morebundles.common.items.BundleHandler.isConcealed(net.minecraft.class_2487)" because the return value of "me.salamander.morebundles.common.items.MoreBundlesInfo.getHandler()" is null

**Comment by BelgianSalamander** [comment]
You are using an old version - try the latest version on curseforge.
